#Created by BGHDDevelopment(Noodles)
#Discord/Support: https://bghddevelopment.com/discord
#Plugin Link: https://www.spigotmc.org/resources/53460
#Website: https://bghddevelopment.com
#Wiki: https://wiki.bghddevelopment.com/books/luckpermsgui
#Ideas/Feedback: https://feedback.bghddevelopment.com/
#=======================================================
#Permssion: luckpermsgui.update
Update:
  Enabled: true
#Enables if there is a message on-join when the plugin is outdated.
#=======================================================
CheckForUpdates:
  Enabled: true
#Enables a message in console if the plugin is outdated.
#=======================================================
SilentStart:
  Enabled: false
#Removes startup messages.
#=======================================================
#Commands:
#/lp gui - Open the GUI
#/lp gui user <user> - Opens an user GUI
#/lp gui group <group> - Opens a group GUI
#Permissions:
#luckperms.gui - Use the GUI
#=======================================================